### ISSUE TITLE
possible improvement on result printout

### ISSUE THREAD

**Issue by dracodoc** [olafmersmann/microbenchmark#3]
I saw many typical usage of microbenchmark are on functions, so the expression is short and the printout looks good. 

Recently I developed a RStudio addin to select some code, click addin menu to run microbenchmark in console. This way I can test my code any time without changes to code, no need to wrap them in function or comment out microbenchmark lines temporarily.

With this usage I often have multiple lines statements as expression input, thus the result printout became messed up.

Is it possible to add a parameter to disable the expression printout? And maybe print the result in a format like Markdown table to make it more aligned?

**Comment by olafmersmann** [comment]
Hi Xianghui,

you can replace the expression printout with a more readable name by naming your expression arguments to microbenchmark(). See:

```
> microbenchmark(sum(rnorm(100)), sum(runif(100)))
Unit: microseconds
            expr    min     lq     mean median     uq    max neval
 sum(rnorm(100)) 14.617 15.239 15.86731 15.550 16.483 23.325   100
 sum(runif(100))  7.775  8.086  9.30825  8.397  8.708 87.702   100
> microbenchmark(a=sum(rnorm(100)), b=sum(runif(100)))
Unit: microseconds
 expr    min     lq     mean median     uq    max neval
    a 14.617 15.239 15.76778 15.550 16.483 19.593   100
    b  7.775  8.086  8.68316  8.397  8.708 20.837   100
```

While there is no markdown support, you could take the data.frame returned by summary.microbenchmark() and format that to your liking. See:

```
> library("knitr")
> res <- microbenchmark(a=sum(rnorm(100)), b=sum(runif(100)))
> kable(summary(res), "markdown")

|expr |   min|    lq|    mean| median|     uq|    max| neval|
|:----|-----:|-----:|-------:|------:|------:|------:|-----:|
|a    | 8.397| 9.019| 9.49178|  9.330| 9.9520| 13.062|   100|
|b    | 4.665| 4.976| 5.31190|  4.976| 5.4425| 24.258|   100|
```

which renders as

| expr | min | lq | mean | median | uq | max | neval |
| :-- | --: | --: | --: | --: | --: | --: | --: |
| a | 8.397 | 9.019 | 9.49178 | 9.330 | 9.9520 | 13.062 | 100 |
| b | 4.665 | 4.976 | 5.31190 | 4.976 | 5.4425 | 24.258 | 100 |

Does that solve your problems?

Cheers,
Olaf

**Comment by dracodoc** [comment]
Perfect! 
I'll update my addin to use the expression name by default. And the markdown solution is great.

Thanks a lot!
